var GLOBAL_PARAM = {};
	//GLOBAL_PARAM.sWidth = 1280;	GLOBAL_PARAM.sHeight = 720;
	GLOBAL_PARAM.sWidth = 1024;
	GLOBAL_PARAM.sHeight = 576;
	GLOBAL_PARAM.scene;
	GLOBAL_PARAM.camera;
	GLOBAL_PARAM.MyRay;

var SHADOWS_ELEMENTS = [];
var SHADOWS_CONTAINS = [];
var PHYSICS_COLLISIONS = [];
var MODELS_COLLISION = [];
var EVENTS_COLLECTION = [];